name: Check with yarn
on: [push, pull_request]
jobs:
  build:
    name: Install and test with yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.16"

        # --ignore engines added due to Yarn Classic bug installing under Node.js 18.x
        # https://github.com/cypress-io/request/issues/89
      - run: yarn install --ignore-engines
      - run: yarn test
